# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xls_pack.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(917, 406)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(320, 40, 571, 341))
        self.plainTextEdit.setUndoRedoEnabled(False)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(21, 41, 281, 341))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_1 = QtWidgets.QLabel(self.widget)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.lineEdit_k = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_k.setObjectName("lineEdit_k")
        self.verticalLayout.addWidget(self.lineEdit_k)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_tk = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_tk.setObjectName("lineEdit_tk")
        self.verticalLayout.addWidget(self.lineEdit_tk)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_uk = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_uk.setObjectName("lineEdit_uk")
        self.verticalLayout.addWidget(self.lineEdit_uk)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_out = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_out.setObjectName("lineEdit_out")
        self.verticalLayout.addWidget(self.lineEdit_out)
        self.checkBox_match = QtWidgets.QCheckBox(self.widget)
        self.checkBox_match.setObjectName("checkBox_match")
        self.verticalLayout.addWidget(self.checkBox_match)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttondup = QtWidgets.QPushButton(self.widget)
        self.buttondup.setObjectName("buttondup")
        self.horizontalLayout_2.addWidget(self.buttondup)
        self.buttonmerge = QtWidgets.QPushButton(self.widget)
        self.buttonmerge.setObjectName("buttonmerge")
        self.horizontalLayout_2.addWidget(self.buttonmerge)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "xls_pack"))
        self.label_4.setText(_translate("Dialog", "共有主键（用空格隔开）"))
        self.label_1.setText(_translate("Dialog", "Shared keys(seperate by a space)"))
        self.label_5.setText(_translate("Dialog", "共有主键类型（用空格隔开）"))
        self.label.setText(_translate("Dialog", "types of the shared keys"))
        self.label_6.setText(_translate("Dialog", "共有候选键（用空格隔开）"))
        self.label_2.setText(_translate("Dialog", "Shared useless keys(seperate by a space)"))
        self.label_7.setText(_translate("Dialog", "输出文件名"))
        self.label_3.setText(_translate("Dialog", "output filename"))
        self.checkBox_match.setText(_translate("Dialog", "排除元数据中不存在的数据\n"
"match keys with metadata"))
        self.buttondup.setText(_translate("Dialog", "排重 Duplicate"))
        self.buttonmerge.setText(_translate("Dialog", "合并 Merge"))

